# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20160901_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vm_set', to='assets.Asset', verbose_name='\u5bbf\u4e3b\u673a'),
        ),
    ]
