# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20160901_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, unique=True, verbose_name='\u540d\u79f0'),
            preserve_default=False,
        ),
    ]
