# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_virtualmachine_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newassetapprovalzone',
            name='approved',
        ),
        migrations.AddField(
            model_name='newassetapprovalzone',
            name='status',
            field=models.CharField(choices=[('Success', '\u5df2\u901a\u8fc7'), ('Failed', '\u5ba1\u6279\u5931\u8d25'), ('NotYet', '\u672a\u5ba1\u6279')], default='NotYet', max_length=64, verbose_name='\u5ba1\u6279\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='asset_type',
            field=models.CharField(blank=True, choices=[('server', '\u670d\u52a1\u5668'), ('network_device', '\u7f51\u7edc\u8bbe\u5907'), ('storage', '\u5b58\u50a8\u8bbe\u5907'), ('software', '\u8f6f\u4ef6\u8d44\u4ea7'), ('virtual_machine', '\u865a\u62df\u673a'), ('others', '\u5176\u5b83\u7c7b')], max_length=64, null=True),
        ),
    ]
